
configuration:
  - Release

platform:
  - Win32
  - x64

install:
  - cinst wget
  - c:\ProgramData\chocolatey\bin\wget.exe http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28-w32-setup.exe
  - c:\ProgramData\chocolatey\bin\wget.exe http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28-w64-setup.exe
  - ps: Install-Package -Force .\libsndfile-1.0.28-w32-setup.exe
  - ps: Install-Package -Force .\libsndfile-1.0.28-w64-setup.exe

build_script:
  - msbuild build\VampSDK.sln
  - msbuild build\VampHostSDK.sln
  
