name: Linux CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'vamp-plugins/vamp-test-plugin'
    - name: deps
      run: |
        sudo apt-get install -y build-essential cmake libsndfile-dev
    - name: make
      run: |
        mkdir build
        cd build
        cmake .. -DVAMPSDK_BUILD_EXAMPLE_PLUGINS=ON -DVAMPSDK_BUILD_SIMPLE_HOST=ON -DVAMPSDK_BUILD_RDFGEN=ON
        make
    - name: test-plugin-regression
      run: ./test/run-test-plugin-regression.sh
